allowBuilds:
  '@nestjs/core': true
  '@parcel/watcher': false
  '@swc/core': true
  unrs-resolver: false
minimumReleaseAgeExclude:
  - vite@8.3.1
  - '@nestjs/cli@12.0.7'
  - '@vitest/coverage-v8@5.0.2'
  - '@vitest/mocker@5.0.2'
  - '@vitest/spy@5.0.2'
  - vitest@5.0.2
onlyBuiltDependencies:
  - '@nestjs/core'
  - '@swc/core'
